### PR TITLE
ShellStream: Write skips a byte when buffer is full

### PR DESCRIPTION
**Pull request by JasonQG**
Fix every 1025th byte being skipped

### CODE REVIEW

**Comment by JasonQG** [comment]
Any chance this could be included in the next release?

**Comment by drieseng** [comment]
I'll merge this once I had time to add a regression test.

**Comment by drieseng** [comment]
I'll be adding tests later today.

**Comment by JasonQG** [comment]
Sorry for the delay in responding. Tested with the beta, and it looks good. Thanks!

**Pull request merged**
