### PR TITLE
Tweak diagnostics

### PR DESCRIPTION
**Pull request by Rob-Hague**
* Make it work (it needs the TRACE symbol defined - lots of head scratching without it)

* Expose publicly, but still in DEBUG (to allow programmatic configuration necessary in Core)

* Document how to use it

* Tweak usage (add some logs, remove key/iv information, override ToString on some Message types)

### CODE REVIEW

**Comment by WojciechNagorski** [comment]
This is a great idea! I'm going to use this in integration tests:
image

**Comment by Rob-Hague** [comment]
@drieseng if you would be willing to give me access to the wiki, I will add some instructions to https://github.com/sshnet/SSH.NET/wiki/Troubleshooting-SSH.NET

**Comment by WojciechNagorski** [comment]
@Rob-Hague @drieseng I wanted to prepare a new web page something similar to https://docs.automapper.org/en/stable/ But I need to admin permissions to https://github.com/sshnet/sshnet.github.io 
Until the first version is released, I don't want to ask for reviews all the time. Too much time.

**Comment by WojciechNagorski** [comment]
@Rob-Hague I made you a maintainer. Please let me know if you can edit right now.
FYI @drieseng

**Comment by Rob-Hague** [comment]
Thanks, I was able to make a test edit. I will update that page

**Comment by zybexXL** [comment]
@Rob-Hague, this doesn't compile for me in RELEASE mode, complains about 'Source' being undefined in [DiagnosticAbstraction.cs:62](https://github.com/sshnet/SSH.NET/pull/1241/files#diff-f19631754fe79bf4609d82b1d44c87ac6acb22e88dff5ab05635c39032883554R62) under Net7.0.

**Comment by Rob-Hague** [comment]
Thanks #1248

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1

**Pull request merged**
