### PR TITLE
For now, by default disable analyzers during build.

### PR DESCRIPTION
**Pull request by drieseng**
For now, by default disable analyzers during build.
Document how to locally enable the analyzers.

### CODE REVIEW

**Comment by drieseng** [comment]
@WojciechNagorski, please review.

**Comment by WojciechNagorski** [comment]
To be honest I don't agree with this change, I think we should run analyzers during build in CD process.

**Comment by zybexXL** [comment]
Why not disable in DEBUG only ? It is somewhat annoying when coding.

**Comment by WojciechNagorski** [comment]
Yes I agree that this is annoying. 
1. If we disable only for debug then when the contributor makes the new PR the build fails. 
2. If we disable analyzers at all - we will merge PRs that do not meet our rules.

Only a developer who makes a lot of changes and often should turn off the analyzers locally. This is only one setting and for an advanced developer it is not a problem. Junior may not be aware of how to turn it off, but if he changes a few lines, he learns more thanks to the analyzers. And there is a greater chance that PR will be built in the pipeline.

**Comment by Rob-Hague** [comment]
I just don't know if we need 4 sets of analyzers (.NET, StyleCop, Meziantou, Sonar) in order to have a coherent code style.

Following this [guide](https://www.meziantou.net/understanding-the-impact-of-roslyn-analyzers-on-the-build-time.htm) a clean build of the solution takes 1min30 on my laptop, with 7min20 of CPU time burnt in Sonar. Both of these numbers are far too high.

image

image

**Comment by Rob-Hague** [comment]
I think ideally we would not enable all analyzers by default with opt-out, instead disabling all by default and opting-in to those that are useful. But practically it would be a good start by disabling those which are not useful and take the most time.

**Review by BTCRob1993 — APPROVED** [review]

**Comment by Rob-Hague** [comment]
I think the dust has settled on this now.

**Pull request closed without merging**
