### PR TITLE
Replace SemaphoreLight with SemaphoreSlim

### PR DESCRIPTION
**Pull request by Rob-Hague**
This paves the way for asynchronous synchronisation via WaitAsync (and eliminates a timing test which sometimes fails in CI)

### CODE REVIEW

**Comment by WojciechNagorski** [comment]
How do you know there is a problem with SemaphoreLight?

**Review by WojciechNagorski — APPROVED** [review]
LGTM! It is stable and I think it's better to use official semaphore.

**Comment by Rob-Hague** [comment]
> How do you know there is a problem with SemaphoreLight?

I looked through the recent builds and saw this one which had failed https://ci.appveyor.com/project/drieseng/ssh-net/builds/48640576/tests. I don't think it will fix any other tests

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1

**Pull request merged**
