### PR TITLE
Handle SSH_MSG_GLOBAL_REQUEST earlier in the connection process

### PR DESCRIPTION
**Pull request by antmeehan**
See #8 

As suggested by Martin Prikryl.

### CODE REVIEW

**Comment by drieseng** [comment]
LGTM, I'll merge once I've added a unit test for it.
Thanks!!

**Comment by drieseng** [comment]
Can you share details on how I can reproduce this issue (server, version, ...) ?

**Comment by trebor-salim** [comment]
I've got the same error on my computer.

Win7 x64
OpenSSH 7.2p2-1-v1 (http://www.mls-software.com/opensshd.html)
sshd_config - default configuration

**Comment by drieseng** [comment]
@trebor-salim If I ever manage to download the installer from that site, I'll try to reproduce and fix this issue.

**Comment by drieseng** [comment]
@trebor-salim I was able to reproduce this issue. I'll apply the PR this weekend, and add a test for it.

**Comment by dnfield** [comment]
I've reproduced this on Windows as well.  Glad to see this is still being worked on.

**Pull request merged**
