### PR TITLE
Add a few spans on net6.0 or greater

### PR DESCRIPTION
**Pull request by Rob-Hague**

### CODE REVIEW

**Comment by Rob-Hague** [comment]
This can wait for more important work.

**Comment by WojciechNagorski** [comment]
Part of this PR is done by https://github.com/sshnet/SSH.NET/pull/1272.

**Comment by Rob-Hague** [comment]
Re-opened for the remainder after #1272 cc @jacobslusser

**Review by WojciechNagorski — APPROVED** [review]
LGTM!

**Pull request merged**
