### PR TITLE
Build with Release configuration

### PR DESCRIPTION
**Pull request by scott-xu**

### CODE REVIEW

**Comment by WojciechNagorski** [comment]
We want to run tests in debug mode.

**Comment by scott-xu** [comment]
Just want to see if it reduces the CI time.
The other thing is, if we want to use CI to generate the nuget package, it has to be Release mode.
Or we can build twice: one for unit test (debug), the other for nuget package (release).

**Comment by WojciechNagorski** [comment]
We need to optimize our tests. For example many tests upload 5mb file, many multiple times. In unit tests we have many thread sleep.

**Comment by WojciechNagorski** [comment]
We want to run our test in the debug mode because we want to have more logs

**Comment by scott-xu** [comment]
Since the unit tests are much more stable now, can we switch to release mode? I ask because we can leverage Appvoyer to build, test and finally [deploy the package to nuget.org](https://www.appveyor.com/docs/deployment/nuget/). @WojciechNagorski @Rob-Hague

**Comment by Rob-Hague** [comment]
I think we should still test in Debug mode, in order to cover various `Debug.Assert` calls. I don't think that stops us from creating a release package in CI(?)

**Comment by WojciechNagorski** [comment]
I agree with Rob. If we want to release test nugget we have to build two times.

**Pull request closed without merging**
