### PR TITLE
Add functionality to communicate with remote commands over stdin

### PR DESCRIPTION
**Pull request by mdarocha**
This is a rebase and update of https://github.com/sshnet/SSH.NET/pull/144, with the sole purpose being adding functionality to communicate with commands executed over ssh using stdin.

This functionality is needed by ie. https://github.com/dotnet/Docker.DotNet/pull/575

This PR reimplements functionality requested in https://github.com/sshnet/SSH.NET/issues/141, InputStream seems to have been lost in the original rewrite PR

### CODE REVIEW

**Comment by WojciechNagorski** [comment]
@drieseng This is a really important issue for the entire .NET. We need this change for [Docker.DotNet](https://www.nuget.org/packages/Docker.DotNet) library that has 9.1M downloads. Currently, no one is able to create a real docker manager using .NET, because it can work only locally or with unsafe remote connections without encryption. Thanks to this PR the community will be able to communicate with Docker via the safe encrypted connection. Can you help with this PR?

**Comment by preetmyob** [comment]
@drieseng  Would you have any idea if you're going to be able to have a look at this PR, please? Your help would really be appreciated. Thank you

**Comment by WojciechNagorski** [comment]
@mdarocha Tests do not pass. Can you check it?

**Comment by mdarocha** [comment]
Unfortunately I don't have the time to work on this PR anymore. I'm closing it, if anybody wants to pick up this work, feel free to do it.

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.

**Comment by WojciechNagorski** [comment]
Fixed by https://github.com/sshnet/SSH.NET/pull/1293

**Pull request closed without merging**
