### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Dlyftservies**

### CODE REVIEW

**Review by Dlyftservies — COMMENTED** [review]
Sshreadme

**Review by Dlyftservies — COMMENTED** [review]
Westit

**Comment by Rob-Hague** [comment]
What's going on here?

**Comment by Dlyftservies** [comment]
Been teaching myself code

**Review by Dlyftservies — COMMENTED** [review]
Well

**Comment by Dlyftservies** [comment]
Awesome, thanks for the update!

**Pull request closed without merging**
