### PR TITLE
WIP: Support for Ed25519 Host- and Private-Keys

### PR DESCRIPTION
**Pull request by darinkes**

### CODE REVIEW

**Comment by bhalbright** [comment]
Wow, this is really nice. You are farther ahead than I was. I think the only area where I have something you don't is I've got the code to decrypt the private key inside the openssh key. Perhaps I could somehow contribute this code to your effort, though I'm honestly not really sure the easiest way to do that in github (commit to your fork?). Regardless I'll spent some time cleaning up the code I had and then I'll commit it to my fork and share the link.

I had wanted to use SSH.NET in a work project about a year ago but the lack of ED25519 support was a showstopper so we had to do something else (wrote a C# wrapper around libssh) but I always wanted to come back and contribute to this project, I finally got around to working on it and it appears you had the same idea!

**Comment by darinkes** [comment]
> Wow, this is really nice. You are farther ahead than I was. I think the only area where I have something you don't is I've got the code to decrypt the private key inside the openssh key. Perhaps I could somehow contribute this code to your effort, though I'm honestly not really sure the easiest way to do that in github (commit to your fork?). Regardless I'll spent some time cleaning up the code I had and then I'll commit it to my fork and share the link.

That would be a huge help! Then I can start working on improving the KEX-Situation, too.

**Comment by bhalbright** [comment]
@darinkes Here is what I had so far, it is only lightly tested however (only walked through a couple unit tests to see if the key parsing works). Let me know what you think, thanks!

[my fork comparison to ssh.net](https://github.com/sshnet/SSH.NET/compare/develop...bhalbright:develop)

**Comment by bhalbright** [comment]
@darinkes I don't know if you've had a chance to look at my fork yet but if you prefer maybe you could make me a contributor on your fork and I could update your impl with the decryption code. I like how you separated the parsing into a separate class anyhow. No rush though, thanks.

**Comment by darinkes** [comment]
@bhalbright I have to do some rework of my approach on EC in SSH.NET.
.NET System.Security.Cryptography failed on the very last step of ECDH to be usable:
https://social.msdn.microsoft.com/Forums/en-US/89060f38-d388-4f38-b6e6-4a31271abef3/ecdh-key-agreement-in-cng-how-to-get-the-raw-agreed-secret

So I'm now checking out other ways to add EC to SSH.NET. It will take some more time.

**Comment by darinkes** [comment]
@bhalbright I cherry-picked your OpenSSH Key-Format Reader into my branch:
https://github.com/darinkes/SSH.NET-1/commit/fb2a0ead641544b8e485982224f834866c0eee05

So it's visible you did the work! 👍 
OK for you?

**Comment by darinkes** [comment]
Closing in favor of: https://github.com/sshnet/SSH.NET/pull/496

**Comment by bhalbright** [comment]
thanks @darinkes  glad I could help out a little!

**Comment by willie84** [comment]
Thanks that this was implemented. It has just saved our 2 day bug . We had generated our keys using rsa but we used ssh-ed25519 and now the keys work on our sftp operation.  Thanks. Cool stuff

**Pull request closed without merging**
