### PR TITLE
Move sending SSH_MSG_KEXINIT to Session.cs from key exchange procedure

### PR DESCRIPTION
**Pull request by Sparin**
Description and main issue:
https://github.com/sshnet/SSH.NET/issues/767#issuecomment-867643938

Optional issues
https://github.com/darkoperator/Posh-SSH/issues/376
https://github.com/sshnet/SSH.NET/issues/778

### CODE REVIEW

**Comment by GlukerTura** [comment]
Hi Sparin! It works (solve the problem with no kexinit on Cisco switches with OpenSSH_7.3p1.RL).
Thanks!

**Comment by pdlove** [comment]
Is this waiting on the tests to be fixed or on something else? I need this for connecting to Cisco devices!

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1

**Pull request closed without merging**
