### PR TITLE
[ECDsa] Falls back to use BouncyCastle if BCL (Mono) doesn't support

### LINKED ISSUE #1406: SSH.Net 2024.0.0 works for UWP but does not work for Android and iOS
### Discussed in https://github.com/sshnet/SSH.NET/discussions/1405

<div type='discussions-op-text'>

<sup>Originally posted by **Karteeka18** May 17, 2024</sup>
We have integrated SSH.Net 2024.0.0 from Nuget for Xamarin UWP, Xamarin. IOS and Mono Android.  UWP works fine. BUT iOS and Android are throwing exceptions. Any ideas or suggestions would be helpful.
Visual Studio 2022 C#

              using (SftpClient sftp = new SftpClient(host, port, user, pass))
                {
                    sftp.Connect();

                    if (!sftp.Exists(path))
                        ok = false;
                    sftp.Disconnect();
                }

Throws an Exception on sftp.Connect().

**iOS Exception** 
{System.NotImplementedException: The method or operation is not implemented.   at System.Security.Cryptography.ECDsa.Create (System.Security.Cryptography.ECParameters parameters) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamari…} </div>

### PR DESCRIPTION
**Pull request by scott-xu**
Fixes https://github.com/sshnet/SSH.NET/issues/1406

### CODE REVIEW

**Comment by Rob-Hague** [comment]
Can we use this for .NET Framework (4.6.2) as well? So that we have 2 implementations instead of 3.

Instead of the `isMono` check, can we wrap the `ECDsa.Create(parameter)` call in a try-catch and then fall back to BouncyCastle? That should capture all the cases where it doesn't work, and still allow using the BCL if later versions of mono support it.

**Comment by scott-xu** [comment]
@Rob-Hague @WojciechNagorski Could you please help re-trigger the CI? Or would you mind granting me permission for Appveyor?

**Comment by Rob-Hague** [comment]
I suppose what I meant was, can we delete the custom CNG implementation so we just have (1) The normal BCL implementation with ECDsa; and if that is not supported then (2) The BouncyCastle implementation

Currently, this does not fix #1406 because #1406 does not use the .NET Framework target (probably .NET Standard instead). You can see that because the failure is on ECDsa.Create which is only called under `#if !NETFRAMEWORK`

**Comment by Rob-Hague** [comment]
> I suppose what I meant was, can we delete the custom CNG implementation so we just have (1) The normal BCL implementation with ECDsa; and if that is not supported then (2) The BouncyCastle implementation

Since that would cause all .NET Framework applications to use BouncyCastle, that is probably not exactly what we want.

I'm finding it difficult to read and understand what implementation is used when. I think we want:

1. If ECDsa.Create(ECParameters) is supported, use that
2. Otherwise, if running on Windows, use CNG
3. Otherwise, use BouncyCastle

But that does complicate the testing situation...

**Comment by scott-xu** [comment]
> > I suppose what I meant was, can we delete the custom CNG implementation so we just have (1) The normal BCL implementation with ECDsa; and if that is not supported then (2) The BouncyCastle implementation
> 
> Since that would cause all .NET Framework applications to use BouncyCastle, that is probably not exactly what we want.
> 
> I'm finding it difficult to read and understand what implementation is used when. I think we want:
> 
> 1. If ECDsa.Create(ECParameters) is supported, use that
> 2. Otherwise, if running on Windows, use CNG
> 3. Otherwise, use BouncyCastle
> 
> But that does complicate the testing situation...

Not sure if anybody uses Mono at Windows... I propose below logic:

1. If NET, use `ECDsa.Create(ECParameters)` without fallback
2. Otherwise if `NETStandard` or `NET47` above, use `ECDsa.Create(ECParameters)` and falls back to BouncyCastle
3. Otherwise if `NET462`, use CNG and falls back to BouncyCastle

**Comment by Rob-Hague** [comment]
I think we are proposing the same thing, so if it's easy to follow in the code, then sounds good

**Comment by scott-xu** [comment]
We don't have NET47 as target framework. (Should we?  `ECDsa.Create(ECParameters)` supports .NET Framework 4.7 onwards, see https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.create?view=net-8.0#system-security-cryptography-ecdsa-create(system-security-cryptography-ecparameters))

Here's current simplified logic:
- `!NET` -> Use BouncyCastle as a fallback
 - `FRAMEWORK` -> Use CNG

**Comment by scott-xu** [comment]
> We don't have NET47 as target framework. (Should we? `ECDsa.Create(ECParameters)` supports .NET Framework 4.7 onwards, see https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.ecdsa.create?view=net-8.0#system-security-cryptography-ecdsa-create(system-security-cryptography-ecparameters))
> 
> Here's current simplified logic:
> 
> * `!NET` -> Use BouncyCastle as a fallback
> * `FRAMEWORK` -> Use CNG

Update:
* `!NET` -> Use BouncyCastle as a fallback
* `NET462` -> Use `CngKey`

**Comment by Rob-Hague** [comment]
Yeah probably makes sense

Is there a way to use the "Impl" pattern here that we have used in other places?

**Comment by scott-xu** [comment]
> Is there a way to use the "Impl" pattern here that we have used in other places?

I tried, but it's a little bit different with others. Anyway it's good to separate into different files.

**Comment by Rob-Hague** [comment]
I iterated on it a bit and tested with a few different configurations. Will just wait for confirmation from mono...

**Review by Rob-Hague — APPROVED** [review]

**Pull request merged**
