### PR TITLE
Correction for issue #562

### PR DESCRIPTION
**Pull request by EricGarnier**
To correct issue #562, use only one ManualResetEvent is SshCommand , which is signaled when the command complete, either on success or on error.
Add also a dispose of this ManualResetEvent.

### CODE REVIEW

**Comment by WojciechNagorski** [comment]
@EricGarnier PR needs refreshing.

**Comment by EricGarnier** [comment]
What do you mean ?
How I am supposed to refresh the PR ?

Thanks for your help.

Eric

**Comment by WojciechNagorski** [comment]
@EricGarnier PR needs to be refreshed due to merge conflicts.

**Comment by EricGarnier** [comment]
Hi @WojciechNagorski ,
I was unable to update the PR, so I create a new one.
#1164 
Sorry for this.

Eric

**Comment by Rob-Hague** [comment]
Closing per https://github.com/sshnet/SSH.NET/issues/562#issuecomment-2168778374 (sorry)

**Pull request closed without merging**
