### PR TITLE
Expose SshIdentificationReceived event

### PR DESCRIPTION
**Pull request by scott-xu**

### CODE REVIEW

**Comment by WojciechNagorski** [comment]
@scott-xu Can you describe why you need this? What is your use case?

**Comment by scott-xu** [comment]
It is described in https://github.com/sshnet/SSH.NET/issues/1191

**Comment by WojciechNagorski** [comment]
@scott-xu How this PR is related with #972 - you mention it here https://github.com/sshnet/SSH.NET/issues/1191#issuecomment-1813534489

Sorry for the questions but sometimes it is hard to understand the relationship between issues and PR.

**Comment by scott-xu** [comment]
@WojciechNagorski With this PR, plus https://github.com/sshnet/SSH.NET/pull/972, lib user can set  `InitiateKeyExchange` to true/false based on server type Cisco/non-Cisco

**Comment by WojciechNagorski** [comment]
@scott-xu I know this, but there are no tests so I would like to know how users will use it. I don't have enough time to figure out how to use it, especially if it is divided into 2 PRs.

If you want me to review and merge this I need unit or integration tests or a description of how to use it.

**Comment by scott-xu** [comment]
@WojciechNagorski Tests are added. I also renamed the event to `ServerIdentificationReceived`.
https://github.com/sshnet/SSH.NET/pull/1195/files#diff-a5e8d1be9212cb37167bf627f1723c331ddaa2cefddd9fa349acd562d8d3325fR16

**Review by WojciechNagorski — APPROVED** [review]
LGTM! I tested it.

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1

**Pull request merged**
