### PR TITLE
Project for Visual Studio 2022

### PR DESCRIPTION
**Pull request by Philippe-Laval**
Project for Visual Studio 2022 (17.3)

### CODE REVIEW

**Comment by A9G-Data-Droid** [comment]
I have tested this and it works!

**Comment by drieseng** [comment]
@Philippe-Laval, doesn't the VS 2019 solution work for you?

**Comment by webprofusion-chrisc** [comment]
@Philippe-Laval if you are not willing to respond to @drieseng this PR should probably be closed.

**Comment by drieseng** [comment]
No feedback from submitter.

**Pull request closed without merging**
