### PR TITLE
Version 2024.0.0

### PR DESCRIPTION
**Pull request by WojciechNagorski**
In this version, we rewrote the entire ShellStream so it's a big version.

### CODE REVIEW

**Comment by jscarle** [comment]
Great collaboration @WojciechNagorski and @Rob-Hague. I'm really pleased with the final result.

**Comment by Rob-Hague** [comment]
Let's hope it works 😁

**Comment by jscarle** [comment]
Bug reports be like...

image

**Comment by WojciechNagorski** [comment]
I'm proud of the final result. Most of it was thanks to you @jscarle, @Rob-Hague, @scott-xu, I almost only checked and approved the changes. You worked so much and so fast that I didn't have time for my own work :wink:

Working with you @mus65, @jacobslusser, @Rob-Hague, @jscarle, @scott-xu, @realvizu is a pure pleasure. 

Tomorrow I will prepare release notes and I will release Nuget.

**Comment by scott-xu** [comment]
Can you please review and merge https://github.com/sshnet/SSH.NET/pull/1332 if possible? @WojciechNagorski

**Comment by WojciechNagorski** [comment]
The new version has been released.
https://twitter.com/WojtekNagorski/status/1760387422989263230
Please retweet and inform wherever possible.

**Pull request merged**
