### PR TITLE
WIP: Run tests both on Windows & Linux

### PR DESCRIPTION
**Pull request by dimhotepus**
* Run tests both on Windows and Linux hosts.

### CODE REVIEW

**Comment by dimhotepus** [comment]
Please, try to run Appveyor on this MR. Trying to add testing on Linux host.

**Comment by Rob-Hague** [comment]
Nice.

Could you please keep it in Debug mode? There are a number of `Debug.Assert` calls that we would want to fire if they were hit.

Could you also try to run the integration tests? I believe the appveyor images have docker installed. I have been wondering if just `dotnet test src/Renci.SshNet.sln` is all that is needed (or if appveyor would even do that automatically without the command)

**Comment by WojciechNagorski** [comment]
@dimhotepus Thanks! Great work. I will use this PR.

**Comment by WojciechNagorski** [comment]
I will continue this work on #1250 
Big thenks @dimhotepus

**Pull request closed without merging**
