### PR TITLE
PR #971 with conflicts resolved and building

### PR DESCRIPTION
**Pull request by et1975**
This brings #971 up to date and hopefully nudging along the solution for #825.

### CODE REVIEW

**Comment by et1975** [comment]
@Rob-Hague or anyone else can comment/approve?

**Comment by Rob-Hague** [comment]
> @Rob-Hague or anyone else can comment/approve?

I don't speak with any authority but I have given this problem some thought so I will leave my opinion here.

It's great that there is a (presumably) working solution already. One can pull down the code and build the library to use it.

However I do not think the implementation is good enough to be merged into the repo, mainly with regard to the duplication of the `RsaKey` and `RsaDigitalSignature` classes. I know why it was done this way: a `Key` is contracted to provide a `DigitalSignature` but all `DigitalSignature` implementations require a `Key`. So you end up with the implementations coupled together. Ideally `RsaDigitalSignature` would take a `HashAlgorithm` (or similar) in the constructor but then this needs to be passed through `RsaKey`, which needn't be concerned with the implementation of a signature.

I think the solution is to remove the `Sign` and `Verify` methods from `Key`: ultimately a key itself does not sign something. But that could be a rather big (breaking) change, including on other types like `KeyHostAlgorithm`. If I think a bit harder I will consider opening an issue with a proposal.

**Comment by WojciechNagorski** [comment]
@et1975 I'm waiting for more permissions for this project and intend to reactivate this project once I get them.

**Comment by WojciechNagorski** [comment]
@Rob-Hague Can you propose your solution/PR? I already have repo and Nuget permissions so we can handle this topic.

**Comment by et1975** [comment]
Closing in favour of #1177

**Comment by WojciechNagorski** [comment]
@et1975 Did you test #1177 ?

**Comment by et1975** [comment]
I'm not using this library directly, will have to see what it means for [Posh-SSH](https://github.com/darkoperator/Posh-SSH/issues/537).

**Comment by WojciechNagorski** [comment]
Ok, we need to test everything and confirm if it's ok and then we'll release it. Then PoshSSH can update.

**Comment by Rob-Hague** [comment]
FYI I have tested it against several different servers (including servers which are not OpenSSH)

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0

**Pull request closed without merging**
