### PR TITLE
Added KeyExchangeDiffieHellmanGroup14Sha256

### LINKED ISSUE #461: Failed to negotiate key exchange algorithm
Hi, I am using 2016.1.0 (from nuget) and I am trying to connect to a TeltonikaRUT955 Modem via SSH. I just updated the firmware to a newer version which has "Improved SSH security" in its changelog. I can no longer login via SSH.NET, only via Putty.

It seems that SSH.NET does not support newer cipher algorithms. Do you know more about this?
Putty logs the following:
```
2018-08-27 12:59:28	We claim version: SSH-2.0-PuTTY_Release_0.70
[...]
2018-08-27 12:59:28	Doing ECDH key exchange with curve Curve25519 and hash SHA-256
[...]
2018-08-27 12:59:30	Initialised AES-256 SDCTR client->server encryption
2018-08-27 12:59:30	Initialised HMAC-SHA-256 client->server MAC algorithm
2018-08-27 12:59:30	Initialised AES-256 SDCTR server->client encryption
2018-08-27 12:59:30	Initialised HMAC-SHA-256 server->client MAC algorithm
[...]
```

The router uses `Dropbear v2018.76` as ssh client.

Downgrading the firmware is not an option in case of the SSH and overall system security.

### PR DESCRIPTION
**Pull request by AtosNicoS**
A colleague of mine has recently implemented the missing algorithm. A connection to the openwrt router mentioned in the issue is now possible.

Fixes https://github.com/sshnet/SSH.NET/issues/461

### CODE REVIEW

**Comment by drieseng** [comment]
This is great, thanks!!

Please also add unit tests for this algorithm. Preferrable using public test data and expect results.

**Comment by AtosNicoS** [comment]
@drieseng I have added unit tests similar to those that were available. The code was mostly just borrowed from the sha1 implementation, so there is not much that could be wrong or different.

I am using the patch with the router in a real world scenario and this is working fine so far.

Edit: I am not sure why those CI checks fail. On my local machine everything is working fine. Maybe because I am using Visual Studio 2017 and the older solutions were not updated?

**Comment by gojimmypi** [comment]
I'm interested in progress on this key exchange PR. Any news? I wonder if perhaps I can help in some way?

**Comment by Psilax** [comment]
Any update on this?

**Comment by drieseng** [comment]
@AtosNicoS Can you resolve the merge conflicts, or are you ok with me integrating your changes?

**Comment by drieseng** [comment]
Integrated in **develop** branch in https://github.com/sshnet/SSH.NET/commit/34df3dd725f4bf98c29a1e5c029cd0741ab27d4a.

**Pull request closed without merging**
