### PR TITLE
Revert mono/.NET Framework integration tests

### PR DESCRIPTION
**Pull request by Rob-Hague**
This combination is not a worthwhile use of time

Ref https://github.com/sshnet/SSH.NET/pull/1458#issuecomment-2267458881 and #1456

### CODE REVIEW

**Review by scott-xu — APPROVED** [review]
It's okay for me.
However, regarding https://github.com/sshnet/SSH.NET/pull/1461, we have to run .NET Framework tests (can use `--filter Name~ECDsa`) at Linux with Mono to verify if it fixes https://github.com/sshnet/SSH.NET/issues/1406.

**Comment by Rob-Hague** [comment]
Ok but note that Xamarin is now EOL, so it also may not be worth your time. And sockets can't run in the browser so mono/WebAssembly is not relevant to us - I don't think there are any officially supported, commonly used scenarios under mono which are relevant to us

**Review by WojciechNagorski — APPROVED** [review]

**Comment by scott-xu** [comment]
Can we keep **Ecdh** and **Zlib**? We need to make sure .NET Framework specific code to be tested.
`--filter "Name~Ecdh|Name~Zlib"`

We don't need to worry about **ChaCha20Poly1305** as there's no .NET Framework specific code for it. It is covered by .NET 8.0 integration test.

**Comment by Rob-Hague** [comment]
If it doesn't cause any issues, then fine. I'll try it on the DSA branch. Otherwise it is easy enough to run them properly locally

**Pull request merged**
